/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import internal.I_Adart;
import internal.I_Hukuman;
import internal.I_Jabatan;
import internal.I_Kegiatan;
import internal.I_Anggota;
import internal.I_ManageAccount;
import internal.I_Proker;
import internal.I_Sekolah;
import java.awt.Component;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;


/**
 *
 * @author kausar
 */
public class F_Admin extends javax.swing.JFrame {

    /**
     * Creates new form F_Anggota
     */
    private String nimsend;
    public F_Admin() {
        initComponents();
        
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSekolah = new javax.swing.JLabel();
        contoh = new javax.swing.JLabel();
        btn_proker = new javax.swing.JLabel();
        btnAgt = new javax.swing.JLabel();
        btnAdart = new javax.swing.JLabel();
        btnJabatan = new javax.swing.JLabel();
        btnHukuman = new javax.swing.JLabel();
        btnKegiatan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();
        WorkSpace = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnSekolah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sekolah.png"))); // NOI18N
        btnSekolah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSekolah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSekolahMouseClicked(evt);
            }
        });

        btn_proker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proker.png"))); // NOI18N
        btn_proker.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_proker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_prokerMouseClicked(evt);
            }
        });

        btnAgt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anggota.png"))); // NOI18N
        btnAgt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgtMouseClicked(evt);
            }
        });

        btnAdart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hkm.png"))); // NOI18N
        btnAdart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdartMouseClicked(evt);
            }
        });

        btnJabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jabatan.png"))); // NOI18N
        btnJabatan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJabatanMouseClicked(evt);
            }
        });

        btnHukuman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hukuman.png"))); // NOI18N
        btnHukuman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHukuman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHukumanMouseClicked(evt);
            }
        });

        btnKegiatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kegiatan.png"))); // NOI18N
        btnKegiatan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKegiatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKegiatanMouseClicked(evt);
            }
        });

        jLabel1.setText("Jabatan");

        jLabel2.setText("Anggota");

        jLabel3.setText("Sekolah");

        jLabel4.setText("Proker");

        jLabel5.setText("Manage Account");

        jLabel6.setText("Hukuman");

        jLabel7.setText("Kegiatan");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manageaccount.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel11.setText("AD/ART");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoff.png"))); // NOI18N
        btn_logout.setToolTipText("Log Out");
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_logout)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgt)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSekolah)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_proker)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJabatan)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHukuman)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKegiatan)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdart)
                    .addComponent(jLabel11))
                .addGap(4, 4, 4)
                .addComponent(contoh)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnAgt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnSekolah)
                .addGap(15, 15, 15)
                .addComponent(jLabel3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_proker)
                .addGap(15, 15, 15)
                .addComponent(jLabel4))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnJabatan)
                .addGap(15, 15, 15)
                .addComponent(jLabel1))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnHukuman)
                .addGap(15, 15, 15)
                .addComponent(jLabel6))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnKegiatan)
                .addGap(15, 15, 15)
                .addComponent(jLabel7))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAdart)
                .addGap(15, 15, 15)
                .addComponent(jLabel11))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(contoh))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(17, 17, 17)
                .addComponent(jLabel5))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        WorkSpace.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout WorkSpaceLayout = new javax.swing.GroupLayout(WorkSpace);
        WorkSpace.setLayout(WorkSpaceLayout);
        WorkSpaceLayout.setHorizontalGroup(
            WorkSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        WorkSpaceLayout.setVerticalGroup(
            WorkSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(WorkSpace, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WorkSpace))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgtMouseClicked
        // TODO add your handling code here:
        I_Anggota in_agt = new I_Anggota();
        in_agt.setVisible(true);
        WorkSpace.add(in_agt);

        try {
            in_agt.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(F_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgtMouseClicked

    private void btn_prokerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prokerMouseClicked
        // TODO add your handling code here:
         I_Proker n_prok = new I_Proker();
        n_prok.setVisible(true);
        WorkSpace.add(n_prok);

        try {
            n_prok.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(F_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_prokerMouseClicked

    private void btnSekolahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSekolahMouseClicked
        // TODO add your handling code here:
        I_Sekolah n_sklh = new I_Sekolah();
        n_sklh.setVisible(true);
        WorkSpace.add(n_sklh);
        try {
            n_sklh.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(F_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSekolahMouseClicked

    private void btnHukumanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHukumanMouseClicked
        // TODO add your handling code here:
         I_Hukuman n_hkm = new I_Hukuman();
        n_hkm.setVisible(true);
        WorkSpace.add(n_hkm);

        try {
            n_hkm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(F_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHukumanMouseClicked

    private void btnJabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJabatanMouseClicked
        // TODO add your handling code here:
        I_Jabatan n_jbt = new I_Jabatan();
        n_jbt.setVisible(true);
        WorkSpace.add(n_jbt);

        try {
            n_jbt.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(F_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnJabatanMouseClicked

    private void btnKegiatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKegiatanMouseClicked
        // TODO add your handling code here:
        I_Kegiatan n_keg = new I_Kegiatan();
        n_keg.setVisible(true);
        WorkSpace.add(n_keg);

        try {
            n_keg.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(F_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKegiatanMouseClicked

    private void btnAdartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdartMouseClicked
        // TODO add your handling code here:
        I_Adart n_Adart = new I_Adart();
        n_Adart.setVisible(true);
        WorkSpace.add(n_Adart);

        try {
            n_Adart.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(F_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdartMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        I_ManageAccount n_manage = new I_ManageAccount();
        n_manage.setVisible(true);
        WorkSpace.add(n_manage);

        try {
            n_manage.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(F_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        F_login fl = new F_login();
        fl.setVisible(true);
    }//GEN-LAST:event_btn_logoutMouseClicked
    
    
    
    public void addWork(Component wrk){
      WorkSpace.add(wrk);
      wrk.setMinimumSize(null);
    }// karena harus meminta data dari form lain, maka dibuatkan method untuk menyimpan data kiriman dari form internal list
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            SwingUtilities.updateComponentTreeUI(new F_Admin());
                   }catch(Exception ex){
                       System.out.println("Gagal");
                   }
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane WorkSpace;
    private javax.swing.JLabel btnAdart;
    private javax.swing.JLabel btnAgt;
    private javax.swing.JLabel btnHukuman;
    private javax.swing.JLabel btnJabatan;
    private javax.swing.JLabel btnKegiatan;
    private javax.swing.JLabel btnSekolah;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_proker;
    private javax.swing.JLabel contoh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
