/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.dialog;

import Controller.CmdAnggota;
import db.ConnectionManager;
import entitas.Anggota;
import internal.I_Anggota;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author kausar
 */
public class D_Anggota extends javax.swing.JDialog {

    /**
     * Creates new form D_NewAnggota
     */
    public D_Anggota(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tampilsemuacombo();
        txtIdJabatan.setVisible(false);
        txtIdSekolah.setVisible(false);
        txtAlamatSklh.setEditable(false);
        txtJobDescJbtn.setEditable(false);
    }
    private String nim;
     public D_Anggota(java.awt.Frame parent, boolean modal, String nim, String nama, String alamat,String no_hp,String email,String angkatan, String id_jabatan, String id_sekolah) {
        super(parent, modal);
        initComponents();
        txtNim.setText(nim);
        txtNama.setText(nama);
        txtAlamat.setText(alamat);
        txtNoHp.setText(no_hp);
        txtEmail.setText(email);
        txtAngkatan.setText(angkatan);
        
        this.nim = nim;
        
        txtIdJabatan.setText(id_jabatan);
        txtIdSekolah.setText(id_sekolah);
        tampilsemuacombo();
        txtIdJabatan.setEditable(false);
        txtIdSekolah.setEditable(false);
        txtAlamatSklh.setEditable(false);
        txtJobDescJbtn.setEditable(false);
    }
   
    
    public void tampilsemuacombo(){
    ConnectionManager conMan=new ConnectionManager();
    Connection conn= conMan.logOn(); 
    
    
    try
    {
  
      String sql ="select * from tbl_sekolah";
      String sql1 ="select * from tbl_jabatan where status = 'Himpunan'";
    
       Statement stm=conn.createStatement();
       ResultSet rs1 = stm.executeQuery(sql);
       while (rs1.next())
       {  
         String nama=rs1.getString("nama");         
         comSekolah.addItem(nama);
       }
       
       Statement stm1=conn.createStatement();
       ResultSet rs2 = stm.executeQuery(sql1);
       while (rs2.next())
       {  
         String nama=rs2.getString("nama");         
         comJabatan.addItem(nama);
       }
       
       }catch (Exception e)
    {
        JOptionPane.showMessageDialog(null, "GAGAL MENAMPILKAN DATA");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNoHp = new javax.swing.JTextField();
        txtAngkatan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamatSklh = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtJobDescJbtn = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comJabatan = new javax.swing.JComboBox();
        comSekolah = new javax.swing.JComboBox();
        txtIdJabatan = new javax.swing.JTextField();
        txtIdSekolah = new javax.swing.JTextField();
        btn_save = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nim");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, -1, -1));
        jPanel1.add(txtNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 220, -1));
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 220, -1));
        jPanel1.add(txtNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 220, -1));
        jPanel1.add(txtAngkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 220, -1));

        txtAlamatSklh.setColumns(20);
        txtAlamatSklh.setRows(5);
        jScrollPane1.setViewportView(txtAlamatSklh);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 300, -1));

        txtJobDescJbtn.setColumns(20);
        txtJobDescJbtn.setRows(5);
        jScrollPane2.setViewportView(txtJobDescJbtn);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 300, 110));

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, -1, -1));

        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel4.setText("No Hp");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel5.setText("Jabatan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 220, -1));

        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel8.setText("Angkatan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel9.setText("Asal Sekolah");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        comJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comJabatanActionPerformed(evt);
            }
        });
        jPanel1.add(comJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 230, -1));

        comSekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comSekolahActionPerformed(evt);
            }
        });
        jPanel1.add(comSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 230, -1));

        txtIdJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdJabatanActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 50, -1));

        txtIdSekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSekolahActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdSekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 50, -1));

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 50, 50));

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane3.setViewportView(txtAlamat);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comJabatanActionPerformed
        // TODO add your handling code here:
        ConnectionManager conMan= new ConnectionManager();
        Connection con =conMan.logOn();
        try
        {
            String sql="select * from tbl_jabatan where nama='"+comJabatan.getSelectedItem()+"'";
            Statement st=con.createStatement();
            ResultSet rs =st.executeQuery(sql);

            while(rs.next())
            {
                txtIdJabatan.setText(rs.getString("id_jabatan"));
                txtJobDescJbtn.setText(rs.getString("jobdesc"));
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_comJabatanActionPerformed

    private void comSekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comSekolahActionPerformed
        // TODO add your handling code here:
        ConnectionManager conMan= new ConnectionManager();
        Connection con =conMan.logOn();
        try
        {
            String sql="select * from tbl_sekolah where nama='"+comSekolah.getSelectedItem()+"'";
            Statement st=con.createStatement();
            ResultSet rs =st.executeQuery(sql);

            while(rs.next())
            {
                txtIdSekolah.setText(rs.getString("id_sekolah"));
                txtAlamatSklh.setText(rs.getString("alamat"));
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_comSekolahActionPerformed

    private void txtIdJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdJabatanActionPerformed

    private void txtIdSekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSekolahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSekolahActionPerformed

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
        // TODO add your handling code here:
        String nim,nama,alamat,no_hp,angkatan,email;
        int id_jabatan,id_sekolah;
        nim = txtNim.getText();
        nama = txtNama.getText();
        alamat = txtAlamat.getText();
        no_hp = txtNoHp.getText();
        email = txtEmail.getText();
        angkatan = txtAngkatan.getText();
        
        id_jabatan = Integer.parseInt(txtIdJabatan.getText());
        id_sekolah = Integer.parseInt(txtIdSekolah.getText());
        
        ConnectionManager conMan = new ConnectionManager();
        Connection conn = conMan.logOn();
       try{
        String sql = "select * from tbl_anggota where nim = '"+this.nim+"'";
        
         Statement st = conn.createStatement();  
         ResultSet rs = st.executeQuery(sql);
         
         rs.next();
         if(rs.getRow() > 0){
          Anggota agt = new Anggota(nim, angkatan, id_jabatan, id_sekolah, nama, alamat, no_hp, email);
          CmdAnggota cAgt = new CmdAnggota();
          cAgt.updateAgt(agt);
          JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        this.dispose();
         }else{
        Anggota agt = new Anggota(nim, angkatan, id_jabatan, id_sekolah, nama, alamat, no_hp, email);
        CmdAnggota cAgt = new CmdAnggota();
        cAgt.saveAgt(agt);
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        this.dispose();
         }
       }
       catch(SQLException e){
           
       }
        

       

        
        
        
    }//GEN-LAST:event_btn_saveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                D_Anggota dialog = new D_Anggota(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_save;
    private javax.swing.JComboBox comJabatan;
    private javax.swing.JComboBox comSekolah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextArea txtAlamatSklh;
    private javax.swing.JTextField txtAngkatan;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdJabatan;
    private javax.swing.JTextField txtIdSekolah;
    private javax.swing.JTextArea txtJobDescJbtn;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtNoHp;
    // End of variables declaration//GEN-END:variables
}
