/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.dialog;

import Controller.CmdPanitia;
import db.ConnectionManager;
import entitas.Exporter;
import entitas.Panitia;
import java.io.File;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author kausar
 */
public class D_Panitia extends javax.swing.JDialog {
private DefaultTableModel model;
    /**
     * Creates new form D_Panitia
     */
    public D_Panitia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public D_Panitia(java.awt.Frame parent, boolean modal, String nim) {
        super(parent, modal);
        initComponents();
        
        model = new DefaultTableModel();

        //menambahkan header tabel
        model.addColumn("NIM");
        model.addColumn("Nama Proker");
        model.addColumn("Tempat");
        model.addColumn("Jabatan");
        model.addColumn("Id Panitia");

        TabelPanitia.setModel(model);
        tampilsemuacombo();
        txtNim.setText(nim);
        txtNim.setEditable(false);
        txtTanggal.setEditable(false);
        txtTujuan.setEditable(false);
        txtIdJabatan.setVisible(false);
        txtIdProker.setVisible(false);
        txtJobdesc.setEditable(false);
        tampilPan();
    }
    
    public void tampilsemuacombo(){
    ConnectionManager conMan=new ConnectionManager();
    Connection conn= conMan.logOn(); 
    
    
    try
    {
  
      String sql ="select * from tbl_proker";
      String sql1 ="select * from tbl_jabatan where status = 'proker'";
     
       Statement stm=conn.createStatement();
       ResultSet rs = stm.executeQuery(sql);
       while (rs.next())
       {  
         String proker=rs.getString("nama_proker");         
         comProker.addItem(proker);
       }
       
       Statement stm1=conn.createStatement();
       ResultSet rs1 = stm1.executeQuery(sql1);
       while (rs1.next())
       {  
         String jabatan=rs1.getString("nama");         
         comJabatan.addItem(jabatan);
       }
       
       
       
       }catch (Exception e)
    {
        JOptionPane.showMessageDialog(null, "GAGAL MENAMPILKAN DATA");
    }
    }

    
     public final void tampilPan() {
       
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
        try {
             ConnectionManager conMan= new ConnectionManager();
            Connection con =conMan.logOn();
            String sql = "select * from tbl_panitia LEFT JOIN tbl_anggota ON tbl_panitia.nim = tbl_anggota.nim LEFT JOIN tbl_jabatan ON tbl_panitia.id_jabatan = tbl_jabatan.id_jabatan LEFT JOIN tbl_proker ON tbl_panitia.id_proker = tbl_proker.id_proker where tbl_panitia.nim = '"+ txtNim.getText() +"'";
            Statement s = con.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            while (r.next()) {
                Object[] o = new Object[5];
                o[0] = r.getString("tbl_anggota.nim");
                o[1] = r.getString("tbl_proker.nama_proker");
                o[2] = r.getString("tbl_proker.tempat");
                o[3] = r.getString("tbl_jabatan.nama");
                o[4] = r.getString("tbl_panitia.id_panitia");
                

                model.addRow(o);
            }
            
            
            r.close();
            s.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelKiri = new javax.swing.JPanel();
        PanelButton = new javax.swing.JPanel();
        btn_save = new javax.swing.JLabel();
        btn_update = new javax.swing.JLabel();
        btn_delete = new javax.swing.JLabel();
        btn_print = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdJabatan = new javax.swing.JTextField();
        comJabatan = new javax.swing.JComboBox();
        txtIdProker = new javax.swing.JTextField();
        comProker = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTujuan = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtJobdesc = new javax.swing.JTextArea();
        txtTanggal = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        PanelKanan = new javax.swing.JPanel();
        btn_search = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelPanitia = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelKiri.setBackground(new java.awt.Color(204, 204, 204));
        PanelKiri.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        PanelButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanelButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });
        PanelButton.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
        });
        PanelButton.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMouseClicked(evt);
            }
        });
        PanelButton.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        btn_print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
        });
        PanelButton.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        PanelButton.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        panelInput.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Jabatan");
        panelInput.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        panelInput.add(txtIdJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 60, -1));

        comJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comJabatanActionPerformed(evt);
            }
        });
        panelInput.add(comJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 200, -1));
        panelInput.add(txtIdProker, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 60, -1));

        comProker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comProkerActionPerformed(evt);
            }
        });
        panelInput.add(comProker, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 200, -1));

        jLabel2.setText("Nim");
        panelInput.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setText("Proker");
        panelInput.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtTujuan.setColumns(20);
        txtTujuan.setRows(5);
        jScrollPane1.setViewportView(txtTujuan);

        panelInput.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 270, 70));

        txtJobdesc.setColumns(20);
        txtJobdesc.setRows(5);
        jScrollPane3.setViewportView(txtJobdesc);

        panelInput.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 270, -1));
        panelInput.add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 270, -1));
        panelInput.add(txtNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 270, -1));

        javax.swing.GroupLayout PanelKiriLayout = new javax.swing.GroupLayout(PanelKiri);
        PanelKiri.setLayout(PanelKiriLayout);
        PanelKiriLayout.setHorizontalGroup(
            PanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        PanelKiriLayout.setVerticalGroup(
            PanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        PanelKanan.setBackground(new java.awt.Color(204, 204, 204));
        PanelKanan.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sSearch.png"))); // NOI18N
        btn_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });

        TabelPanitia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nim", "Nama", "Jabatan", "Proker", "Id_Jabatan", "Id_Proker", "Id_Pantia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelPanitia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabelPanitiaMousePressed(evt);
            }
        });
        TabelPanitia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TabelPanitiaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(TabelPanitia);

        javax.swing.GroupLayout PanelKananLayout = new javax.swing.GroupLayout(PanelKanan);
        PanelKanan.setLayout(PanelKananLayout);
        PanelKananLayout.setHorizontalGroup(
            PanelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKananLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_search)))
                .addContainerGap())
        );
        PanelKananLayout.setVerticalGroup(
            PanelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_search)
                    .addGroup(PanelKananLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelKiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelKiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
        // TODO add your handling code here:
        String nim;
        int id_jabatan,id_proker;

        nim = txtNim.getText();
        id_jabatan = Integer.parseInt(txtIdJabatan.getText());
        id_proker = Integer.parseInt(txtIdProker.getText());

        Panitia pan = new Panitia(nim, id_proker, id_jabatan);
        CmdPanitia cPan = new CmdPanitia();
        cPan.savePan(pan);
        JOptionPane.showMessageDialog(null, "Data tersimpan");
        tampilPan();
    }//GEN-LAST:event_btn_saveMouseClicked

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseClicked
        // TODO add your handling code here:
        int row = TabelPanitia.getSelectedRow();
        String nim,Strid_panitia;
        
        int id_proker,id_jabatan,id_panitia;

        nim = txtNim.getText();
        id_proker = Integer.parseInt(txtIdProker.getText());
        id_jabatan = Integer.parseInt(txtIdJabatan.getText());
        Strid_panitia = (String) TabelPanitia.getValueAt(row, 4);
        id_panitia = Integer.parseInt(Strid_panitia);

        Panitia pan = new Panitia(nim, id_proker, id_jabatan,id_panitia);
        CmdPanitia cPan = new CmdPanitia();
        cPan.updatePan(pan);
        JOptionPane.showMessageDialog(null, "Data tersimpan = ");
        tampilPan();

    }//GEN-LAST:event_btn_updateMouseClicked

    private void btn_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseClicked
        // TODO add your handling code here:
        int row = TabelPanitia.getSelectedRow();

        int id_panitia;
        String Strid_panitia;

        Strid_panitia =(String) TabelPanitia.getValueAt(row, 4);
        id_panitia = Integer.parseInt(Strid_panitia);

        CmdPanitia cPan = new CmdPanitia();
        cPan.deletePan(id_panitia);
        JOptionPane.showMessageDialog(null, "Data terhapus");
        tampilPan();
    }//GEN-LAST:event_btn_deleteMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void comJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comJabatanActionPerformed
        // TODO add your handling code here:
        ConnectionManager conMan= new ConnectionManager();
        Connection con =conMan.logOn();
        try
        {
            String sql="select * from tbl_jabatan where nama='"+comJabatan.getSelectedItem()+"'";
            Statement st=con.createStatement();
            ResultSet rs =st.executeQuery(sql);

            while(rs.next())
            {
                txtIdJabatan.setText(rs.getString("id_jabatan"));
                txtJobdesc.setText(rs.getString("jobdesc"));
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_comJabatanActionPerformed

    private void comProkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comProkerActionPerformed
        // TODO add your handling code here:
        ConnectionManager conMan= new ConnectionManager();
        Connection con =conMan.logOn();
        try
        {
            String sql="select * from tbl_proker where nama_proker='"+comProker.getSelectedItem()+"'";
            Statement st=con.createStatement();
            ResultSet rs =st.executeQuery(sql);

            while(rs.next())
            {
                txtIdProker.setText(rs.getString("id_proker"));
                txtTujuan.setText(rs.getString("tujuan"));
                txtTanggal.setText(rs.getString("tanggal"));
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_comProkerActionPerformed
public void cari_data(JTable tbl, String text){
        TableRowSorter sorter = new TableRowSorter(tbl.getModel());
        tbl.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        tbl.setSelectionMode(1);
}
    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        // TODO add your handling code here:
         cari_data(TabelPanitia, (String)txtSearch.getText());

    }//GEN-LAST:event_btn_searchMouseClicked

    private void TabelPanitiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPanitiaMousePressed
        // TODO add your handling code here:
        int row = TabelPanitia.getSelectedRow();
        String nim,proker,jabatan;

        
        jabatan = TabelPanitia.getValueAt(row, 3).toString();
        proker = TabelPanitia.getValueAt(row, 1).toString();

        
        comJabatan.setSelectedItem(jabatan);
        comProker.setSelectedItem(proker);
    }//GEN-LAST:event_TabelPanitiaMousePressed

    private void TabelPanitiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelPanitiaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelPanitiaKeyPressed

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
        // TODO add your handling code here:
        if (TabelPanitia.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Tidak ada data");
        }
        
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Export ke excell"," .xls");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Save");
        chooser.setMultiSelectionEnabled(false);
        chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION){
                List<JTable> tb = new ArrayList<>();
            List<String>nom = new ArrayList<>();
            tb.add(TabelPanitia);
            nom.add("Laporan Panitia");
            String file = chooser.getSelectedFile().toString().concat(".xls");
            try {
                Exporter e = new Exporter(new File(file) , tb , nom);
               
                if(e.export()){
                    JOptionPane.showMessageDialog(null, "Berhasil Export","Export To Excell",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null, "ada yang error" +ex.getMessage(), "Error", 
                        JOptionPane.ERROR_MESSAGE);
            }
            }
    }//GEN-LAST:event_btn_printMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_Panitia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_Panitia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_Panitia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_Panitia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                D_Panitia dialog = new D_Panitia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelButton;
    private javax.swing.JPanel PanelKanan;
    private javax.swing.JPanel PanelKiri;
    private javax.swing.JTable TabelPanitia;
    private javax.swing.JLabel btn_delete;
    private javax.swing.JLabel btn_print;
    private javax.swing.JLabel btn_save;
    private javax.swing.JLabel btn_search;
    private javax.swing.JLabel btn_update;
    private javax.swing.JComboBox comJabatan;
    private javax.swing.JComboBox comProker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelInput;
    private javax.swing.JTextField txtIdJabatan;
    private javax.swing.JTextField txtIdProker;
    private javax.swing.JTextArea txtJobdesc;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextArea txtTujuan;
    // End of variables declaration//GEN-END:variables
}
