/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal;
import entitas.Anggota;
import Controller.CmdAnggota;
import db.ConnectionManager;
import Controller.HitungAktif;
import entitas.Exporter;
import gui.dialog.D_Panitia;
import gui.dialog.D_Pelanggaran;
import gui.dialog.D_Prestasi;
import gui.dialog.D_Anggota;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author kausar
 */
public class I_Anggota extends javax.swing.JInternalFrame {

    /**
     * Creates new form I_ListAnggota
     */
    
    
    public I_Anggota() {
        initComponents();
        hitung();
        showAnggota();
        
       
    }
    
    public void showAnggota(){
    
        CmdAnggota cAgt = new CmdAnggota();
        ArrayList<Anggota> myAgt = cAgt.getAllAgt();
        
        Object[][] dtAgt = new Object[myAgt.size()][11];
        int mySize = 0;
        for(Anggota agt : myAgt){
            
            dtAgt[mySize][0] = agt.getNim();
            dtAgt[mySize][1] = agt.getNama();
            dtAgt[mySize][2] = agt.getAlamat();
            dtAgt[mySize][3] = agt.getNo_hp();
            dtAgt[mySize][4] = agt.getEmail();
            dtAgt[mySize][5] = agt.getAngkatan();
            dtAgt[mySize][6] = agt.getStatus();
            dtAgt[mySize][7] = agt.getJabatan();
            dtAgt[mySize][8] = agt.getNama_sekolah();
            dtAgt[mySize][9] = agt.getId_sekolah();
            dtAgt[mySize][10] = agt.getId_jabatan();
            mySize++;
            
        }
       TabelAnggota.setModel(new javax.swing.table.DefaultTableModel(
          /**  new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            }**/dtAgt,
            new String [] {
                "Nim", "Nama", "Alamat", "No Hp", "Email", "Angkatan", "Status", "jabatan", "Nama Sekolah", "Id Sekolah", "Id Jabatan"
            }
        ));
        jScrollPane1.setViewportView(TabelAnggota);
        if (TabelAnggota.getColumnModel().getColumnCount() > 0) {
            TabelAnggota.getColumnModel().getColumn(9).setMinWidth(0);
            TabelAnggota.getColumnModel().getColumn(9).setMaxWidth(0);
            TabelAnggota.getColumnModel().getColumn(10).setMinWidth(0);
            TabelAnggota.getColumnModel().getColumn(10).setMaxWidth(0);
        }
        
    }
    
    
    public void hitung(){
        
    ConnectionManager conMan=new ConnectionManager();
    Connection conn= conMan.logOn(); 
    
    
    try
    {
  
    String sql ="select * from tbl_anggota";
    
       Statement stm=conn.createStatement();
       ResultSet rs = stm.executeQuery(sql);   
       while (rs.next())
       {  
         String nim=rs.getString("nim");
         String angkatan = rs.getString("angkatan");
         HitungAktif ha = new HitungAktif();
         CmdAnggota cAgt = new CmdAnggota();
         String status = ha.hitung(nim, angkatan);
         cAgt.updateStatus(status, nim);
         System.out.println(status);
       }
       
       }catch (Exception e)
    {
        System.out.println(e);
        JOptionPane.showMessageDialog(null, "GAGAL UPDATE");
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelAnggota = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_update = new javax.swing.JLabel();
        btn_delete = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPanitia = new javax.swing.JLabel();
        btnPrestasi = new javax.swing.JLabel();
        btnHukum = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TabelAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nim", "Nama", "Alamat", "No Hp", "Email", "Angkatan", "Status", "Nama Sekolah", "Jabatan", "Id Sekolah", "Id Jabatan"
            }
        ));
        TabelAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelAnggota);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        btn_update.setToolTipText("Update Anggota");
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
        });

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btn_delete.setToolTipText("Dekete Anggota");
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new1.png"))); // NOI18N
        jLabel3.setToolTipText("Tambah Angggota");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        jLabel4.setToolTipText("Print");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });

        btnPanitia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panitia.png"))); // NOI18N
        btnPanitia.setToolTipText("Kepanitiaan");
        btnPanitia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPanitia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPanitiaMouseClicked(evt);
            }
        });

        btnPrestasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prestasi1.png"))); // NOI18N
        btnPrestasi.setToolTipText("Prestasi");
        btnPrestasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrestasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrestasiMouseClicked(evt);
            }
        });

        btnHukum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hkm.png"))); // NOI18N
        btnHukum.setToolTipText("Pelanggaran");
        btnHukum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHukum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHukumMouseClicked(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        btnRefresh.setToolTipText("Kepanitiaan");
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_update)
                    .addComponent(btn_delete)
                    .addComponent(btnHukum)
                    .addComponent(btnPrestasi)
                    .addComponent(btnPanitia))
                .addGap(55, 55, 55))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(btnRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHukum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrestasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPanitia)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sSearch.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void TabelAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelAnggotaMouseClicked
        // TODO add your handling code here:  
        
    }//GEN-LAST:event_TabelAnggotaMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
       new D_Anggota(null, closable).setVisible(true);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseClicked
        // TODO add your handling code here:
        int row = TabelAnggota.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Pilih data dulu");
            
        }else{
        
        String nim;
        
        nim = TabelAnggota.getValueAt(row, 0).toString();
        
        CmdAnggota cAgt = new CmdAnggota();
        cAgt.deleteAgt(nim);
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        showAnggota();
        }
    }//GEN-LAST:event_btn_deleteMouseClicked

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseClicked
        // TODO add your handling code here:
      
        int row = TabelAnggota.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Pilih data dulu");
            
        }else{
        String nim, nama, alamat, no_hp, email, angkatan, id_jabatan,id_sekolah;
        nim = TabelAnggota.getValueAt(row, 0).toString();
        nama = TabelAnggota.getValueAt(row, 1).toString();
        alamat = TabelAnggota.getValueAt(row, 2).toString();
        no_hp = TabelAnggota.getValueAt(row, 3).toString();
        email = TabelAnggota.getValueAt(row, 4).toString();
        angkatan = TabelAnggota.getValueAt(row, 5).toString();
        id_jabatan = TabelAnggota.getValueAt(row, 9).toString();
        id_sekolah = TabelAnggota.getValueAt(row, 10).toString();
        
        D_Anggota updAgt = new D_Anggota(null, closable, nim, nama, alamat, no_hp, email, angkatan, id_jabatan, id_sekolah);
        updAgt.setVisible(true);
            
        }
        
    }//GEN-LAST:event_btn_updateMouseClicked

    private void btnPanitiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanitiaMouseClicked
        // TODO add your handling code here:
        int row = TabelAnggota.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Pilih data dulu");
            
        }else{
        String nim;
        nim = TabelAnggota.getValueAt(row, 0).toString();
        
        
        D_Panitia Pan = new D_Panitia(null, closable, nim);
        Pan.setVisible(true);
            
        }
    }//GEN-LAST:event_btnPanitiaMouseClicked

    private void btnPrestasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestasiMouseClicked
        // TODO add your handling code here:
        int row = TabelAnggota.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Pilih data dulu");
            
        }else{
        String nim;
        nim = TabelAnggota.getValueAt(row, 0).toString();
        
        
        D_Prestasi Pres = new D_Prestasi(null, closable, nim);
        Pres.setVisible(true);
        }  
    }//GEN-LAST:event_btnPrestasiMouseClicked

    private void btnHukumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHukumMouseClicked
        int row = TabelAnggota.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Pilih data dulu");
            
        }else{
        String nim;
        nim = TabelAnggota.getValueAt(row, 0).toString();
        
        
        D_Pelanggaran Huk = new D_Pelanggaran(null, closable, nim);
        Huk.setVisible(true);
        }  
    }//GEN-LAST:event_btnHukumMouseClicked

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        // TODO add your handling code here:
        
        hitung();
        showAnggota();
    }//GEN-LAST:event_btnRefreshMouseClicked
 public void cari_data(JTable tbl, String text){
        TableRowSorter sorter = new TableRowSorter(tbl.getModel());
        tbl.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        tbl.setSelectionMode(1);
}
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
         cari_data(TabelAnggota, (String)txtSearch.getText());
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
          if (TabelAnggota.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Tidak ada data");
        }
        
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Export ke excell"," .xls");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Save");
        chooser.setMultiSelectionEnabled(false);
        chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION){
                List<JTable> tb = new ArrayList<>();
            List<String>nom = new ArrayList<>();
            tb.add(TabelAnggota);
            nom.add("Views Data Anggota");
            String file = chooser.getSelectedFile().toString().concat(".xls");
            try {
                Exporter e = new Exporter(new File(file) , tb , nom);
               
                if(e.export()){
                    JOptionPane.showMessageDialog(null, "Berhasil Export","Export To Excell", JOptionPane.INFORMATION_MESSAGE);
                }
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null, "ada yang error" +ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            } 
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelAnggota;
    private javax.swing.JLabel btnHukum;
    private javax.swing.JLabel btnPanitia;
    private javax.swing.JLabel btnPrestasi;
    private javax.swing.JLabel btnRefresh;
    private javax.swing.JLabel btn_delete;
    private javax.swing.JLabel btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
